package yaml

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/daniilsintsov/harnest-universal/internal/managedfile"
	"github.com/daniilsintsov/harnest-universal/internal/mapping"
	goyaml "gopkg.in/yaml.v3"
)

const (
	configFileName = "harnest.yaml"

	fileHeader = `# harnest.yaml — declarative configuration for the Harnest CLI.
# Generated by Harnest. Edit freely; run 'harnest generate' to apply changes.
# Documentation: see the README bundled with this Harnest build.
`
)

// Load reads and parses harnest.yaml from the given directory.
// Returns an error if the file does not exist, cannot be parsed, or specifies
// an unsupported version.
func Load(dir string) (*HarnestConfig, error) {
	path := filepath.Join(dir, configFileName)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("harnest.yaml not found in %s: run 'harnest init' to create one", dir)
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	var cfg HarnestConfig
	if err := goyaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}

	if cfg.Version != 1 && cfg.Version != CurrentVersion {
		return nil, fmt.Errorf(
			"unsupported harnest.yaml version %d (supported: 1, %d)",
			cfg.Version, CurrentVersion,
		)
	}

	return &cfg, nil
}

// Save marshals cfg to YAML and writes it to harnest.yaml in the given directory.
// The output file is prefixed with a descriptive header comment.
func Save(dir string, cfg *HarnestConfig) error {
	if cfg == nil {
		return fmt.Errorf("cannot save nil config")
	}

	data, err := goyaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	path := filepath.Join(dir, configFileName)
	content := fileHeader + "\n" + string(data)

	if err := managedfile.WriteAtomic(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// Exists reports whether harnest.yaml is present in the given directory.
func Exists(dir string) bool {
	info, err := os.Stat(filepath.Join(dir, configFileName))
	return err == nil && !info.IsDir()
}

// ToAgentConfig converts a HarnestConfig into a mapping.AgentConfig that can
// be passed directly to harness generators.
func (cfg *HarnestConfig) ToAgentConfig() mapping.AgentConfig {
	return cfg.Agents.ToAgentConfig()
}

// ToAgentConfig converts an AgentsBlock into a mapping.AgentConfig.
func (block AgentsBlock) ToAgentConfig() mapping.AgentConfig {
	ac := mapping.AgentConfig{
		Models: make(map[string]string),
	}

	// Consilium: preserve declaration order by iterating the map in a stable way.
	// We build a slice from the map so generators receive a deterministic list.
	for role, agent := range block.Consilium {
		ac.Consilium = append(ac.Consilium, mapping.ConsiliumRole{
			Role:  role,
			Agent: agent,
		})
	}

	// Executing agents.
	for _, e := range block.Executing {
		ac.Exec = append(ac.Exec, mapping.ExecAgent{
			Agent: e.Agent,
			Scope: e.Scope,
		})
	}

	// Model tiers: start from defaults, then apply overrides from config.
	defaults := mapping.DefaultModelTiers()
	for role, tier := range defaults {
		ac.Models[role] = tier
	}
	for role, tier := range block.Models {
		ac.Models[role] = tier
	}

	return ac
}

// AgentBlockFromConfig converts a mapping.AgentConfig into an AgentsBlock.
func AgentBlockFromConfig(cfg mapping.AgentConfig) AgentsBlock {
	block := AgentsBlock{
		Consilium: map[string]string{},
		Models:    map[string]string{},
	}
	for _, role := range cfg.Consilium {
		if role.Agent != "" {
			block.Consilium[role.Role] = role.Agent
		}
	}
	for _, agent := range cfg.Exec {
		if agent.Agent != "" {
			block.Executing = append(block.Executing, ExecEntry{
				Agent: agent.Agent,
				Scope: agent.Scope,
			})
		}
	}
	for role, tier := range cfg.Models {
		if tier != "" {
			block.Models[role] = tier
		}
	}
	if len(block.Consilium) == 0 {
		block.Consilium = nil
	}
	if len(block.Models) == 0 {
		block.Models = nil
	}
	return block
}
